export default function PrivacyPolicy() {
    return (
        <section className="flex justify-center px-4 sm:px-6 lg:px-8">
            <div className="flex flex-col w-full max-w-[1080px] min-h-screen justify-center items-center">
                <h1 className="text-2xl mt-8 sm:mt-16 mb-6 sm:mb-10 font-bold text-center">Privacy Policy<br></br>Effective Date:20/09/2024</h1>
                <div className="flex flex-col w-full h-full text-wrap mb-8 sm:mb-12">
                    <h2 className="font-semibold mb-4 sm:mb-8 mt-3 sm:mt-5 text-xl sm:text-2xl font-serif">Welcome to MUA - Your Ultimate Makeup Artist Booking App</h2>
                    <p className="text-base sm:text-xl font-serif mb-4 sm:mb-6">At MUA, we believe that everyone deserves to look and feel their best, whether it&apos;s for a special occasion, a night out, or just because. We understand that finding the right makeup artist can be a challenge, and that&apos;s why we created MUA - to simplify the process and bring the best makeup artists in India right to your fingertips.</p>
                    <h2 className="font-semibold mb-4 sm:mb-8 mt-3 sm:mt-5 text-xl sm:text-2xl font-serif">Introduction</h2>
                    <p className="text-base sm:text-xl font-serif mb-4 sm:mb-6">MUA Business App is committed to protecting the privacy of our users. This Privacy Policy explains how we collect, use, disclose, and protect your personal information when you use our makeup artist booking app MUA - Book Your Makeup Artist. By using the App, you agree to the collection and use of your information in accordance with this Privacy Policy.</p>
                    <h2 className="font-semibold mb-4 sm:mb-8 mt-3 sm:mt-5 text-xl sm:text-2xl font-serif">Information We Collect</h2>
                    <p className="text-base sm:text-xl font-serif mb-4 sm:mb-6">We collect several types of information to provide and improve our services to you:</p>
                    <p className="text-base sm:text-xl font-serif mb-4 sm:mb-6"><span className="font-semibold">Personal Information</span> Contact Information: Name, phone number, email address (collected during account registration or while contacting a makeup artist).Communication Data: Phone call or WhatsApp communication records when you interact with makeup artists via the App.</p>
                    <p className="text-base sm:text-xl font-serif mb-4 sm:mb-6"><span className="font-semibold">Usage Information</span> Device Information: IP address, browser type, device identifiers, and operating system details. App Activity: Information about how you use the App, such as the artists you view, booking history, and interactions with app features.</p>
                    <p className="text-base sm:text-xl font-serif mb-4 sm:mb-6"><span className="font-semibold">Location Information</span> Geo-location Data: With your permission, we may collect your location to show nearby makeup artists or services. You can disable this in your device settings.</p>
                    <p className="text-base sm:text-xl font-serif mb-4 sm:mb-6"><span className="font-semibold">Files permission</span> Our app needs files access to create user profile.</p>
                    <h2 className="font-semibold mb-4 sm:mb-8 mt-3 sm:mt-5 text-xl sm:text-2xl font-serif">How We Use Your Information</h2>
                    <h2 className="font-normal mb-4 sm:mb-8 mt-3 sm:mt-5 text-base sm:text-xl font-serif">We use the information we collect for the following purposes:</h2>
                    <p className="text-base sm:text-xl font-serif mb-4 sm:mb-6">To Provide Services: Enabling you to browse, contact, and book makeup artists. Communication: Facilitating direct communication between you and makeup artists via phone or WhatsApp. Customer Support: Responding to your inquiries, resolving issues, and providing updates related to the App. Improvement and Development: Improving the App's functionality and user experience. Marketing: With your consent, we may send promotional messages, offers, or recommendations related to makeup services.</p>
                    <h2 className="font-semibold mb-4 sm:mb-8 mt-3 sm:mt-5 text-xl sm:text-2xl font-serif">How We Share Your Information</h2>
                    <h2 className="font-normal mb-4 sm:mb-8 mt-3 sm:mt-5 text-base sm:text-xl font-serif">We may share your information in the following circumstances:</h2>
                    <p className="text-base sm:text-xl font-serif mb-4 sm:mb-6">With Makeup Artists: Your contact information is shared with makeup artists when you initiate contact (via call or WhatsApp). Service Providers: We may use third-party services to help with app hosting, analytics, or customer support. These third parties may have access to your personal information but only to the extent necessary to perform their services. Legal Requirements: We may disclose your information if required by law, such as in response to a court order, legal process, or government request</p>
                    <h2 className="font-semibold mb-4 sm:mb-8 mt-3 sm:mt-5 text-xl sm:text-2xl font-serif">Your Data Protection Rights</h2>
                    <h2 className="font-normal mb-4 sm:mb-8 mt-3 sm:mt-5 text-base sm:text-xl font-serif">Depending on your location, you may have the following rights:</h2>
                    <p className="text-base sm:text-xl font-serif mb-4 sm:mb-6">Access: You can request a copy of the personal information we have about you. Correction: You can ask us to correct inaccurate or incomplete data. Deletion: You can request that we delete your personal information. Objection: You can object to our processing of your personal information for marketing purposes. Withdrawal of Consent: You can withdraw your consent to our data collection and processing at any time. To exercise these rights, please contact us at [Insert Contact Email].</p>
                    <h2 className="font-semibold mb-4 sm:mb-8 mt-3 sm:mt-5 text-xl sm:text-2xl font-serif">Security of Your Information</h2>
                    <p className="text-base sm:text-xl font-serif mb-4 sm:mb-6">We take appropriate security measures to protect your personal information against unauthorized access, disclosure, or destruction. However, no method of transmission over the internet is 100% secure. While we strive to use commercially acceptable means to protect your data, we cannot guarantee absolute security.</p>
                    <h2 className="font-semibold mb-4 sm:mb-8 mt-3 sm:mt-5 text-xl sm:text-2xl font-serif">Children's Privacy</h2>
                    <p className="text-base sm:text-xl font-serif mb-4 sm:mb-6">Our App is not intended for use by individuals under the age of 16. We do not knowingly collect personal information from children. If you believe we have inadvertently collected information from a child, please contact us so we can promptly delete it.</p>
                    <h2 className="font-semibold mb-4 sm:mb-8 mt-3 sm:mt-5 text-xl sm:text-2xl font-serif">Third-Party Links</h2>
                    <p className="text-base sm:text-xl font-serif mb-4 sm:mb-6">The App may contain links to third-party websites or services (e.g., WhatsApp for messaging). We are not responsible for the privacy practices of these third parties, and we encourage you to read their privacy policies.</p>
                    <h2 className="font-semibold mb-4 sm:mb-8 mt-3 sm:mt-5 text-xl sm:text-2xl font-serif">Changes to This Privacy Policy </h2>
                    <p className="text-base sm:text-xl font-serif mb-4 sm:mb-6">We may update this Privacy Policy from time to time. We will notify you of any changes by posting the updated policy in the App or via email. Please review this policy periodically for any updates.</p>
                    <h2 className="font-semibold mb-4 sm:mb-8 mt-3 sm:mt-5 text-xl sm:text-2xl font-serif">Contact Us </h2>
                    <p className="text-base sm:text-xl font-serif mb-4 sm:mb-6">If you have any questions or concerns about this Privacy Policy or how we handle your personal information, please contact us at:</p>
                    <p className="text-base sm:text-xl font-serif mb-4 sm:mb-6">Email  : customerservice@bookyourmua.com</p>
                    <p className="text-base sm:text-xl font-serif mb-4 sm:mb-6">Phone : +91 7620973892</p>
                </div>
            </div>
        </section>
    )
}